### ISSUE TITLE
error calling api.pcloud.com/userInfo

### ISSUE THREAD

**Issue by azndoodle** [gdomenici/plugin.video.pcloud-video-streaming#32] opened 2020-12-29 19:34 UTC
running ver 1.4.2 on Kodi 18.4 and error occurred when entering pcloud account.
Event Log logged error as "Error: cannot logon to pCloud: Error calling userInfo: Unknown error".

**Comment by swabfu** [comment] 2021-01-07 14:23
I have the exact same issue, dunno how to fix it. Tried reinstalling the add-on a few times. I have a free account, and the account works everywhere else I log into. Maybe I have to install from .zip instead of inside the Kodi app?

**Comment by gdomenici** [comment] 2021-01-07 14:32
> running ver 1.4.2 on Kodi 18.4 and error occurred when entering pcloud account.
> Event Log logged error as "Error: cannot logon to pCloud: Error calling userInfo: Unknown error".

Hi @azndoodle , @swabfu 

I'll take a look. It could well be that PCloud changed something in their logon API; haven't tried for a while.

May i have info from you on what platform you're on? Windows, Mac, Android, etc., and what version of that platform?

Kind regards,

Guido

**Comment by swabfu** [comment] 2021-01-07 15:20
> > running ver 1.4.2 on Kodi 18.4 and error occurred when entering pcloud account.
> 
> > Event Log logged error as "Error: cannot logon to pCloud: Error calling userInfo: Unknown error".
> 
> 
> 
> Hi @azndoodle , @swabfu 
> 
> 
> 
> I'll take a look. It could well be that PCloud changed something in their logon API; haven't tried for a while.
> 
> 
> 
> May i have info from you on what platform you're on? Windows, Mac, Android, etc., and what version of that platform?
> 
> 
> 
> Kind regards,
> 
> 
> 
> Guido

Hey Guido,
I'm using the latest stable Kodi build (18.9) and version 1.4.2 of pCloud. Windows 10, version 20H2. If there's anything else I can help you with, just let me know.
Thanks in advance

**Comment by gdomenici** [comment] 2021-01-07 20:44
> I'm using the latest stable Kodi build (18.9) and version 1.4.2 of pCloud. Windows 10, version 20H2. If there's anything else I can help you with, just let me know.

Hi @swabfu ,

Thanks for the information. Alas, I cannot reproduce the error - for me it works fine with the exact configuration you describe. But maybe try these steps:

* Go to the directory C:\Users\YOUR_USERNAME\AppData\Roaming\Kodi\userdata\addon_data
* Delete its subfolder `plugin.video.pcloud-video-streaming`
* Then go to the directory C:\Users\YOUR_USERNAME\AppData\Roaming\Kodi\addons
* Delete its subfolder `plugin.video.pcloud-video-streaming`
* Reinstall the add-on from the repo

By doing these exact steps, at least for me it worked. And of course please double-check your credentials on the pcloud.com website.

Good luck and let me know. I'll leave this issue open until you confirm whether the above has worked.

Kind regards,

Guido

**Comment by azndoodle** [comment] 2021-01-07 22:26
Hi @gdomenici,

Sorry for the late reply, In my case I was trying it on Nvidia Shield and mac osx Big Sur. 

I have a paid pcloud account and I notice there is a 2-step authentication when I login through the web. Not sure if that's relevant. I can try to open a free account and try as well to see if there's a difference.

**Comment by swabfu** [comment] 2021-01-07 22:28
> > I'm using the latest stable Kodi build (18.9) and version 1.4.2 of pCloud. Windows 10, version 20H2. If there's anything else I can help you with, just let me know.
> 
> 
> 
> Hi @swabfu ,
> 
> 
> 
> Thanks for the information. Alas, I cannot reproduce the error - for me it works fine with the exact configuration you describe. But maybe try these steps:
> 
> 
> 
> * Ensure Kodi is not running
> 
> * Go to the directory C:\Users\YOUR_USERNAME\AppData\Roaming\Kodi\userdata\addon_data
> 
> * Delete its subfolder `plugin.video.pcloud-video-streaming`
> 
> * Then go to the directory C:\Users\YOUR_USERNAME\AppData\Roaming\Kodi\addons
> 
> * Delete its subfolder `plugin.video.pcloud-video-streaming`
> 
> * Start Kodi
> 
> * Reinstall the add-on from the repo
> 
> 
> 
> By doing these exact steps, at least for me it worked. And of course please double-check your credentials on the pcloud.com website.
> 
> 
> 
> Good luck and let me know. I'll leave this issue open until you confirm whether the above has worked.
> 
> 
> 
> Kind regards,
> 
> 
> 
> Guido

Hey,
I followed your steps and it works now, thanks :)

**Comment by gdomenici** [comment] 2021-01-18 08:05
> Hey,
> I followed your steps and it works now, thanks :)

Hi @swabfu ,
You're welcome. Thanks for the confirmation.

Hi @azndoodle ,
If it's about 2-factor authentication (2FA) we're potentially in trouble. PCloud simply doesn't let you use 2FA via the API, which is what we use behind the scenes in the plugin. [These guys](https://github.com/PhilippC/keepass2android/issues/605) (unrelated project, but also using the PCloud API) seem to have the same problem.

I have now shot an email to the PCloud support team to ask if there's some way after all. If they confirm it's not possible, I'm afraid we'll have to close this. But let's see.

Kind regards,

Guido

**Comment by gdomenici** [comment] 2021-01-20 08:03
Hi @azndoodle 

> I have now shot an email to the PCloud support team to ask if there's some way after all. If they confirm it's not possible, I'm afraid we'll have to close this. But let's see.

The PCloud support team stated that "The 2FA is not possible with API. If an user has 2FA enabled, he won't be able to access pCloud from other 3rd party apps."

So, unfortunately, it looks like we cannot enable 2FA in the plugin. Sorry about that. Closing this issue.

Kind regards,

Guido

**Closed by gdomenici** 2021-01-20 08:03 UTC
