### ISSUE TITLE
Cannot go back to the main directory

### ISSUE THREAD

**Issue by gkapan** [gdomenici/plugin.video.pcloud-video-streaming#27] opened 2020-04-07 10:00 UTC
Using 1.4.1 with Leia 18.6 and Nolimits. It is not possible to go back to the root directory of pCloud and the only way to bypass this is to uninstall and reinstall and logon again. All of the sudden the system gets you to a directory that has no "Go to Parent" and when you go back you just exit the add-on. If you want me to reproduce it somehow or submit a video let me know

**Comment by gdomenici** [comment] 2020-04-25 20:11
Hi @gkapan 
Indeed, it would help me if you had a reproduction case handy... I have tried to repro it myself, but it seems to work OK - I can always navigate my way to the root folder.
Kind regards,
Guido

**Comment by gkapan** [comment] 2020-05-29 14:29
Back to parent folder does not exist. Chrck this video. The two dots to go back do not work as “go to parent”

https://u.pcloud.link/publink/show?code=XZaOYtkZlTkRgzyQoj4Xw1brKqDCxRFClu97

**Comment by gkapan** [comment] 2020-05-30 04:52
OK, after uninstalling and installing back, “back to parent folder” has returned :) this is my workaround kerpimg the settings when it happens
![DBB7D308-C52C-43C7-94AD-BCA79B27B741](https://user-images.githubusercontent.com/63290144/83319833-76a49a80-a24a-11ea-88bf-603101151925.jpeg)

**Comment by gkapan** [comment] 2020-05-30 04:56
Here you can see that “back to parent folder” is not also on the top because numbers are higher in sorting. Another option is to have “back to parent folder” always under the dots on the top or simply make the dots to go back and after you go to the root to exit :)
![19A7367B-54BF-4C19-B4B3-DE45A7D0A027](https://user-images.githubusercontent.com/63290144/83319920-1530fb80-a24b-11ea-8eba-60209eefa666.jpeg)

**Comment by gdomenici** [comment] 2020-06-07 15:48
Hi @gkapan 

Good catch - indeed, it sorts alphabetically. I'll see whether it's possible to lose the ".." or, if not at least make sure that "Back to parent folder" always sorts on top.

Kind regards,

Guido

**Comment by gdomenici** [comment] 2020-06-07 19:59
Hi @gkapan ,

In fact, the issue is elusive, coz it doesn't reproduce on the "en-us" locale, i.e. if your Kodi language is set to US English. I could, however, reproduce it by setting the Kodi language to "English - New Zealand" (and possibly other ones, too).

At any rate, now it's fixed in 1.4.2, which I just released on GitHub -- see [Releases tab](https://github.com/gdomenici/plugin.video.pcloud-video-streaming/releases). It will also be in the main Kodi addon repo in the next few days.

Kind regards,

Guido

**Closed by gdomenici** 2020-06-07 19:59 UTC
